### ISSUE TITLE
KOORDINAT.fejlmeld skal autopopuleres ved skrivning

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE#265]
indset_koordinat() sætter ikke fejlmeldt-feltet til `false`, så når man siger fx.

    fire info punkt ARGI

Så fører nyindlagte koordinater til:

    ValueError: None is not a valid Boolean

    File "B:\2020\Projects\FIRE\FIRE\fire\cli\info.py", line 396, in punkt
        punkt_fuld_rapport(punkt, punkt.ident, i + 1, n, obs, koord, detaljeret)
    File "B:\2020\Projects\FIRE\FIRE\fire\cli\info.py", line 293, in punkt_fuld_rapport
        koordinatrapport(punkt.koordinater, opt_koord)

Eller med fuldt traceback:

    Traceback (most recent call last):
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\Scripts\fire-script.py", line 33, in <module>
        sys.exit(load_entry_point('fire', 'console_scripts', 'fire')())
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\click\core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\click\core.py", line 782, in main
        rv = self.invoke(ctx)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\click\core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\click\core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\click\core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\click\core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "B:\2020\Projects\FIRE\FIRE\fire\cli\info.py", line 396, in punkt
        punkt_fuld_rapport(punkt, punkt.ident, i + 1, n, obs, koord, detaljeret)
      File "B:\2020\Projects\FIRE\FIRE\fire\cli\info.py", line 293, in punkt_fuld_rapport
        koordinatrapport(punkt.koordinater, opt_koord)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\attributes.py", line 242, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\attributes.py", line 601, in get
        value = self.callable_(state, passive)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\strategies.py", line 631, in _load_for_state
        session, state, primary_key_identity, passive)
      File "<string>", line 1, in <lambda>
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\strategies.py", line 771, in _emit_lazyload
        with_post_criteria(set_default_params).all()
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\ext\baked.py", line 457, in all
        return list(self)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\loading.py", line 98, in instances
        util.raise_from_cause(err)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
        raise value
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\loading.py", line 79, in instances
        rows = [proc(row) for row in fetch]
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\loading.py", line 79, in <listcomp>
        rows = [proc(row) for row in fetch]
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\loading.py", line 511, in _instance
        loaded_instance, populate_existing, populators)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\orm\loading.py", line 611, in _populate_full
        dict_[key] = getter(row)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\site-packages\sqlalchemy\sql\type_api.py", line 1230, in process
        return process_value(value, dialect)
      File "B:\2020\Projects\FIRE\FIRE\fire\api\model\__init__.py", line 27, in process_result_value
        return self._enumtype(value)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\enum.py", line 315, in __call__
        return cls.__new__(cls, value)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\enum.py", line 569, in __new__
        raise exc
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\enum.py", line 553, in __new__
        result = cls._missing_(value)
      File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\fire-dev\lib\enum.py", line 582, in _missing_
        raise ValueError("%r is not a valid %s" % (value, cls.__name__))
    ValueError: None is not a valid Boolean

**Comment by kbevers** [comment]
> indset_koordinat() sætter ikke fejlmeldt-feltet til false

Det skal den nu heller ikke, `fejlmeldt` burde defaulte til `Boolean.FALSE` og må i øvrigt ikke være NULL:

https://github.com/Kortforsyningen/FIRE/blob/3ebe8ee0375ab1566c0f6d6e74e14fdf6c95a2c4/fire/api/model/punkttyper.py#L307-L327

Har du selv opdateret koordinater på ARGI eller er du bare stødt på problemet tilfældigt? Hvis det sidste, så er det nok bare en migrationsfejl. Eller rettere, et lappeløsningsfejl inden migration køres igen.

**Comment by kbevers** [comment]
Jeg kan se at de pågældende koordinater er indsat d. 30/9. Få dage efter `fejlmeldt` er indført. Der er sandsynligvis sket det, at nye koordinater er indlæst med en ældre version af koden. Jeg fikser det lige med lidt SQL bagom API'et.

**Comment by kbevers** [comment]
Og nu er tabellen også opdateret sådan at NULL værdier ikke kan indsættes i `fejlmeldt`. Så er der vist ikke mere jeg kan gøre før en ny migration er kørt. Jeg lukker den her, åben gerne igen hvis du støder på flere problemer af samme slags.

**Comment by busstoptaktik** [comment]
> Jeg kan se at de pågældende koordinater er indsat d. 30/9. Få dage efter fejlmeldt er indført. Der er sandsynligvis sket det, at nye koordinater er indlæst med en ældre version af koden. Jeg fikser det lige med lidt SQL bagom API'et.

Jo - jeg havde egentlig ikke regnet med at "fejlmeldt" ville dukke op før en nymigrering, så jeg var lidt forbavset, da jeg så den. Men man bliver hele tiden klogere :-)

Problemet må gælde i hvert fald et par håndfulde koordinater indsat hen over de sidste halvanden uge

**Comment by busstoptaktik** [comment]
Jep - det fungerer nu. Tak for det!
