### ISSUE TITLE
Rækkefølge ved installation

### ISSUE THREAD

**Issue by larsnaesbye** [Kortforsyningen/FIRE#407]
I installationsdokumentationen angives at man kan teste FIRE version før `fire.ini` er placeret. Dette medfører en 'Konfigurationsfil ikke fundet!' fejl.

```
(fire) C:\FIRE>fire --version
Traceback (most recent call last):
  File "C:\Users\b025966\Miniconda3\envs\fire\Scripts\fire-script.py", line 33, in <module>
    sys.exit(load_entry_point('fire', 'console_scripts', 'fire')())
  File "C:\Users\b025966\Miniconda3\envs\fire\lib\site-packages\pkg_resources\__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\b025966\Miniconda3\envs\fire\lib\site-packages\pkg_resources\__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "C:\Users\b025966\Miniconda3\envs\fire\lib\site-packages\pkg_resources\__init__.py", line 2472, in load
    return self.resolve()
  File "C:\Users\b025966\Miniconda3\envs\fire\lib\site-packages\pkg_resources\__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\FIRE\fire\cli\__init__.py", line 5, in <module>
    firedb = FireDb()
  File "C:\FIRE\fire\api\firedb.py", line 54, in __init__
    self.config = self._read_config()
  File "C:\FIRE\fire\api\firedb.py", line 489, in _read_config
    raise EnvironmentError("Konfigurationsfil ikke fundet!")
OSError: Konfigurationsfil ikke fundet!
```

Burde bekræftelsen af installationen ikke komme efter konfigurationsfilens placering?

**Comment by kbevers** [comment]
> Burde bekræftelsen af installationen ikke komme efter konfigurationsfilens placering?

Jo, det skal bare fikses.
