### ISSUE TITLE
læs-observationer giver fejlmeddelelse men ingen observationer eller punkter i excel arket

### ISSUE THREAD

**Issue by ErikLysdal** [Kortforsyningen/FIRE#573]
Afvikles kommandoen: "fire niv læs-observationer KDI_delstrækning"
vises alle fikspunkter på skærmen incl manglende returmåling, manglende kote mv
indlæsningen afsluttes med beskededen:

Traceback (most recent call last):
  File "C:\Users\b035685\Miniconda3\envs\fire\Scripts\fire-script.py", line 33, in <module>
    sys.exit(load_entry_point('fire', 'console_scripts', 'fire')())
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\fire\fire\fire\cli\niv\_læs_observationer.py", line 65, in læs_observationer
    punktoversigt = opbyg_punktoversigt(projektnavn, nyetablerede, alle_punkter)
  File "c:\fire\fire\fire\cli\niv\_læs_observationer.py", line 241, in opbyg_punktoversigt
    λ, φ = normaliser_lokationskoordinat(
  File "c:\fire\fire\fire\api\model\geometry.py", line 249, in normaliser_lokationskoordinat
    if pd.isna(λ) or pd.isna(φ) or 0 == λ or 0 == φ:
  File "C:\Users\b035685\Miniconda3\envs\fire\lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Projekt excel filen opdateres ikke med observationer eller punkter, så der kan ikke foretages nivellementsberegning i øjeblikket.

Eksemplet er fundet under
F:\GRF\Data\GEO\BC\Niv_Opgaver\2021\NIVEAU_KDI_VESTKYST
hvor der arbejdes med projektet KDI_DELSTRÆKNING

**Comment by kbevers** [comment]
Problemet opstår fordi de to nye punkter endnu ikke er lagt i databasen. Programmet burde kunne håndtere det og komme med følgende advarsel:

```
> fire niv læs-observationer --db=prod KDI_delstrækning
Der mangler landsnumre til nyetablerede punkter.
Har du husket at lægge dem i databasen?
Fortsætter beregningen med brug af de foreløbige navne
Importerer observationer
...
```

Det sker desværre ikke pga en fejl. Der er et fiks på vej i #574. Indtil det lander i en release er her to mulige løsninger:

1. læg de nye punkter i databasen før observationerne læses
2. hvis ikke 1 er en mulighed kan der arbejdes videre med dette regneark jeg har lavet med min version af fire hvor fejlen er rettet: [KDI_delstrækning.xlsx](https://github.com/Kortforsyningen/FIRE/files/8086810/KDI_delstraekning.xlsx)
